esphome:
  name: plc-01
  friendly_name: PLC-01
  platformio_options:
    board_build.flash_mode: dio

esp32:
  board: esp32-s3-devkitc-1
  framework:
    type: arduino

logger:
api:
ota:
  - platform: esphome

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

captive_portal:
uart:
  - id: uart_485
    baud_rate: 115200
    tx_pin: 16
    rx_pin: 15

modbus:
  - id: mb_main
    uart_id: uart_485

modbus_controller:
  - id: mbc_0x01
    address: 0x1
    modbus_id: mb_main
    update_interval: 50ms
    setup_priority: -10

binary_sensor:
  - platform: modbus_controller
    modbus_controller_id: mbc_0x01
    id: mbc_0x01_input_0x01
  - platform: modbus_controller
    modbus_controller_id: mbc_0x01
    id: mbc_0x01_input_0x02
  - platform: modbus_controller
    modbus_controller_id: mbc_0x01
    id: mbc_0x01_input_0x03

cover: