name: editor-for-esphome
services:
  editor-for-esphome:
    image: morcatko/esphome-editor:latest
    container_name: editor-for-esphome
    environment:
      - ESPHOME_URL=        #fill your esphome url
    ports:
      - 8080:3000
    volumes:
      - ./:/app/work-folder/devices